
permalink: /:year/:month/:day/:title.html
highlighter: pygments
paginate: 8
paginate_path: /page:num

markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]

title: 丁小样同学
url: http://blog.dinghz.com
description: 丁小样同学博客，是记录博主学习和成长的一个技术博客。关注于web开发、Java和linux等的技术研究！
keywords: java,linux,shell,mysql,spring,phonegap,redis,oracle,html5,css3
author :
  name : 丁小样同学
  email : crane.ding@163.com
domain: blog.dinghz.com
feed: /rss.xml

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 笔迹
    url: /navigations/archives.html
  - text: 作品
    url: /navigations/works.html
  - text: 关于
    url: /navigations/contact.html

# 评论
disqus:
  config: true
  id: craneding
