
permalink: /:year/:month/:day/:title.html
highlighter: pygments
paginate: 8
paginate_path: /page:num

markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]

title: 丁小样同学
url: http://blog.dinghz.com
description: 丁小样同学博客
keywords: 丁小样同学,个人博客,技术,java
author :
  name : 丁小样同学
  email : crane.ding@163.com
domain: blog.dinghz.com

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /navigations/archives.html
  - text: 作品
    url: /navigations/works.html
  - text: 联系我
    url: /navigations/contact.html
  - text: 友情链接
    url: /navigations/links.html

# 评论
disqus:
  config: true
  id: craneding
